# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ZumBox
                                 A QGIS plugin
 Urban planning related tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-02-07
        copyright            : (C) 2024 by Matjaž Mori, ZUM d.o.o.
        email                : matjaz.mori@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Matjaž Mori, ZUM d.o.o.'
__date__ = '2024-02-07'
__copyright__ = '(C) 2024 by Matjaž Mori, ZUM d.o.o.'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ZumBox class from file ZumBox.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .zum_box import ZumBoxPlugin
    return ZumBoxPlugin()
